const state = { incomes: [], customers: [], vehicles: [], services: [], queue: [], queueReady: true, selectedQueue: null, lastReceipt: null, calendarCursor: new Date(), selectedCalendarDate: '' };
const currency = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 });
const API_BASE = location.protocol === 'file:' ? 'http://localhost:3000/api' : '/api';
const api = async (path, options = {}) => { const response = await fetch(`${API_BASE}${path}`, { headers: { 'Content-Type': 'application/json' }, ...options }); if (!response.ok) { const result = await response.json().catch(() => ({})); let details = result.error; if (typeof details === 'string') { try { details = JSON.parse(details); } catch {} } if (details?.code === '42501') throw new Error(path.startsWith('/antrian') ? 'Izin antrean belum aktif. Jalankan database/operational-features.sql di Supabase SQL Editor.' : 'Izin input master/transaksi belum aktif. Jalankan database/enable-master-inserts.sql di Supabase SQL Editor.'); throw new Error(details?.message || details || 'Permintaan gagal'); } return response.json(); };
const formatDate = value => new Intl.DateTimeFormat('id-ID', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(`${value}T00:00:00`));
const today = () => { const date = new Date(); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; };
state.selectedCalendarDate = today();
const pageTitles = { dashboard: 'Ringkasan', pendapatan: 'Pendapatan', layanan: 'Layanan Bengkel', master: 'Data Master' };
function setPage(page = 'dashboard') { const activePage = pageTitles[page] ? page : 'dashboard'; document.body.dataset.page = activePage; document.getElementById('page-title').textContent = pageTitles[activePage]; document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item.getAttribute('href') === `#${activePage}`)); }
function fillSelect(id, items, label) { const select = document.getElementById(id); select.innerHTML = `<option value="">Pilih ${label}</option>` + items.map(item => `<option value="${item.id}">${item.nama || item.nomor_polisi || item.nama_layanan}</option>`).join(''); }
function fillVehicleSelect(customerId = '') { const vehicles = customerId ? state.vehicles.filter(vehicle => vehicle.pelanggan_id === customerId) : state.vehicles; fillSelect('vehicle-id', vehicles, 'kendaraan'); }
function fillMasterOwnerSelect() { fillSelect('new-vehicle-owner', state.customers, 'pemilik'); }
function formData(form) { return Object.fromEntries(new FormData(form).entries()); }
async function saveMaster(formId, endpoint, messageId) { const form = document.getElementById(formId); const message = document.getElementById(messageId); form.addEventListener('submit', async event => { event.preventDefault(); message.textContent = ''; try { await api(endpoint, { method: 'POST', body: JSON.stringify(formData(form)) }); form.reset(); message.style.color = '#3d9863'; message.textContent = 'Data berhasil disimpan.'; await loadData(); fillQueueFormOptions(); } catch (error) { message.style.color = 'var(--red)'; message.textContent = error.message; } }); }
function updateMetrics() { const month = today().slice(0, 7); const day = today(); const monthRows = state.incomes.filter(row => row.tanggal.startsWith(month)); const todayRows = state.incomes.filter(row => row.tanggal === day); const sum = rows => rows.reduce((total, row) => total + Number(row.total), 0); document.getElementById('month-income').textContent = currency.format(sum(monthRows)); document.getElementById('month-count').textContent = `${monthRows.length} transaksi tercatat`; document.getElementById('today-income').textContent = currency.format(sum(todayRows)); document.getElementById('today-count').textContent = `${todayRows.length} transaksi hari ini`; document.getElementById('total-count').textContent = state.incomes.length; document.getElementById('service-count').textContent = state.services.length; }
function renderTransactions() { const body = document.getElementById('transaction-list'); if (!state.incomes.length) { body.innerHTML = '<tr><td colspan="5" class="empty-state">Belum ada transaksi pendapatan.</td></tr>'; return; } body.innerHTML = state.incomes.slice(0, 8).map(row => `<tr><td>${row.nomor_transaksi}</td><td>${row.pelanggan?.nama || '-'}</td><td>${row.layanan?.nama_layanan || '-'}</td><td>${formatDate(row.tanggal)}</td><td class="align-right amount">${currency.format(row.total)}</td></tr>`).join(''); }
function renderServices() { document.getElementById('service-list').innerHTML = state.services.map(service => `<div class="service-row"><span class="service-name"><i class="service-bullet"></i>${service.nama_layanan}</span><span class="service-price">${currency.format(service.harga_standar)}</span></div>`).join('') || '<p class="muted">Belum ada layanan.</p>'; }
function renderChart() { const days = Number(document.getElementById('period-filter').value); const end = new Date(); const points = []; for (let index = days - 1; index >= 0; index -= 1) { const date = new Date(end); date.setDate(end.getDate() - index); const key = dateKey(date); points.push({ key, label: new Intl.DateTimeFormat('id-ID', { day: '2-digit', month: 'short' }).format(date), value: state.incomes.filter(row => row.tanggal === key).reduce((sum, row) => sum + Number(row.total), 0) }); } const max = Math.max(...points.map(point => point.value), 1); const coords = points.map((point, index) => `${(index / Math.max(points.length - 1, 1)) * 700},${190 - (point.value / max) * 165}`); const line = coords.join(' L '); document.getElementById('chart-line').setAttribute('d', `M ${line}`); document.getElementById('chart-area-fill').setAttribute('d', `M ${coords[0]} L ${line} L 700,200 L 0,200 Z`); document.getElementById('chart-points').innerHTML = points.map((point, index) => `<circle class="chart-pulse" cx="${(index / Math.max(points.length - 1, 1)) * 700}" cy="${190 - (point.value / max) * 165}" r="4"/>`).join(''); document.getElementById('chart-labels').innerHTML = points.filter((_, index) => index === 0 || index === Math.floor(points.length / 2) || index === points.length - 1).map(point => `<span>${point.label}</span>`).join(''); }
async function loadData() { try { const [incomes, customers, vehicles, services] = await Promise.all([api('/pendapatan'), api('/pelanggan'), api('/kendaraan'), api('/layanan')]); Object.assign(state, { incomes, customers, vehicles, services }); fillSelect('customer-id', customers, 'pelanggan'); fillVehicleSelect(); fillMasterOwnerSelect(); fillSelect('service-id', services, 'layanan'); updateMetrics(); renderTransactions(); renderServices(); renderChart(); document.getElementById('connection-status').textContent = 'Terhubung'; document.getElementById('footer-status').textContent = 'Terhubung'; } catch (error) { document.getElementById('connection-status').textContent = 'Belum terhubung'; document.getElementById('footer-status').textContent = 'Periksa konfigurasi'; document.getElementById('transaction-list').innerHTML = `<tr><td colspan="5" class="empty-state">${error.message}. Isi konfigurasi Supabase di backend/app.js.</td></tr>`; } }
document.getElementById('customer-id').addEventListener('change', event => { fillVehicleSelect(event.target.value); });
saveMaster('customer-form', '/pelanggan', 'customer-message'); saveMaster('vehicle-form', '/kendaraan', 'vehicle-message'); saveMaster('service-form', '/layanan', 'service-message');
document.getElementById('income-form').addEventListener('submit', async event => { event.preventDefault(); const message = document.getElementById('form-message'); message.textContent = ''; const payload = { pelanggan_id: document.getElementById('customer-id').value, kendaraan_id: document.getElementById('vehicle-id').value, layanan_id: document.getElementById('service-id').value, total: Number(document.getElementById('amount').value), tanggal: document.getElementById('income-date').value }; try { await api('/pendapatan', { method: 'POST', body: JSON.stringify(payload) }); event.target.reset(); document.getElementById('income-date').value = today(); message.style.color = '#3d9863'; message.textContent = 'Transaksi berhasil disimpan.'; await loadData(); } catch (error) { message.textContent = error.message; } });
document.getElementById('refresh-button').addEventListener('click', loadData); document.getElementById('period-filter').addEventListener('change', renderChart); document.getElementById('today-label').textContent = new Intl.DateTimeFormat('id-ID', { dateStyle: 'full' }).format(new Date()); document.getElementById('income-date').value = today(); loadData().then(() => { fillQueueFormOptions(); loadOperations(); reportRows(); });
window.addEventListener('hashchange', () => setPage(window.location.hash.slice(1))); setPage(window.location.hash.slice(1) || 'dashboard');

const dateKey = value => { const date = value instanceof Date ? value : new Date(value); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; };
const safe = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
const queueDate = item => dateKey(item.jadwal_mulai);
function updateOperationalMetrics() { const day = today(); document.getElementById('working-count').textContent = state.queue.filter(item => item.status === 'dikerjakan').length; document.getElementById('waiting-count').textContent = state.queue.filter(item => item.status === 'menunggu' && queueDate(item) === day).length; }
function renderCalendar() { const cursor = state.calendarCursor; const year = cursor.getFullYear(); const month = cursor.getMonth(); document.getElementById('calendar-month').textContent = new Intl.DateTimeFormat('id-ID', { month: 'long', year: 'numeric' }).format(cursor); const first = new Date(year, month, 1); const startOffset = (first.getDay() + 6) % 7; const daysCount = new Date(year, month + 1, 0).getDate(); const counts = {}; state.queue.forEach(item => { const key = queueDate(item); if (item.status !== 'dipanggil') counts[key] = (counts[key] || 0) + 1; }); const cells = Array.from({ length: startOffset }, () => '<button class="blank" tabindex="-1"></button>'); for (let day = 1; day <= daysCount; day += 1) { const key = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`; const count = counts[key] || 0; const density = count >= 6 ? 'high' : count >= 3 ? 'medium' : 'low'; const classes = [`density-${density}`, key === today() ? 'today' : '', key === state.selectedCalendarDate ? 'selected' : ''].filter(Boolean).join(' '); cells.push(`<button class="${classes}" data-calendar-date="${key}" title="${count} unit terjadwal">${day}${count ? `<small>${count}</small>` : ''}</button>`); } document.getElementById('calendar-days').innerHTML = cells.join(''); renderSelectedDay(); }
function renderSelectedDay() { const key = state.selectedCalendarDate; const selected = new Date(`${key}T12:00:00`); const count = state.queue.filter(item => queueDate(item) === key && item.status !== 'dipanggil').length; const status = count >= 6 ? 'Penuh / ramai' : count >= 3 ? 'Sedang' : 'Low / tersedia'; document.getElementById('selected-day-title').textContent = new Intl.DateTimeFormat('id-ID', { weekday: 'long', day: 'numeric', month: 'long' }).format(selected); document.getElementById('selected-day-detail').textContent = `${status} · kapasitas operasional 8 unit per hari`; document.getElementById('selected-day-count').textContent = `${count} unit terjadwal`; const fill = document.getElementById('capacity-fill'); fill.style.width = `${Math.min(count / 8 * 100, 100)}%`; fill.style.background = count >= 6 ? '#ca6555' : count >= 3 ? '#dda93f' : '#67a778'; }
function phoneNumber(phone) { let digits = String(phone || '').replace(/\D/g, ''); if (digits.startsWith('0')) digits = `62${digits.slice(1)}`; return digits; }
function whatsappLink(item, message) { return `https://wa.me/${phoneNumber(item.pelanggan?.no_telepon)}?text=${encodeURIComponent(message)}`; }
function callCustomer(item) { const overlay = document.createElement('div'); overlay.className = 'call-screen'; overlay.innerHTML = `<div><p class="eyebrow">PANGGILAN PELANGGAN</p><strong>${safe(item.nomor_tiket)}</strong><h2>${safe(item.pelanggan?.nama)}</h2><p>${safe(item.kendaraan?.nomor_polisi)} · silakan menuju loket</p><button type="button">Tutup</button></div>`; overlay.querySelector('button').addEventListener('click', () => overlay.remove()); document.body.append(overlay); if ('speechSynthesis' in window) { const utterance = new SpeechSynthesisUtterance(`Nomor antrean ${item.nomor_tiket}. ${item.pelanggan?.nama}, silakan menuju loket.`); utterance.lang = 'id-ID'; window.speechSynthesis.speak(utterance); } }
function statusButton(item) { if (item.status === 'menunggu') return `<button data-queue-status="dikerjakan" data-queue-id="${safe(item.id)}">Mulai pengerjaan</button>`; if (item.status === 'dikerjakan') return `<button data-queue-status="selesai" data-queue-id="${safe(item.id)}">Tandai selesai</button>`; if (item.status === 'selesai') return `<button data-call-id="${safe(item.id)}">Panggil pelanggan</button>`; return '<span class="queue-status">Sudah dipanggil</span>'; }
function renderQueueCard(item) { const estimateHours = Number(item.layanan?.estimasi_jam || 1); const started = item.waktu_mulai ? new Date(item.waktu_mulai) : null; const eta = started ? new Date(started.getTime() + estimateHours * 3600000) : null; const remaining = eta ? Math.max(0, eta - Date.now()) : 0; const timeText = started ? remaining ? `Sisa ${Math.floor(remaining / 3600000)}j ${Math.floor(remaining % 3600000 / 60000)}m` : 'Lewat estimasi' : `Estimasi ${estimateHours} jam`; const message = `Halo ${item.pelanggan?.nama}, pengerjaan ${item.kendaraan?.nomor_polisi} (${item.layanan?.nama_layanan}) sudah selesai dan siap diambil di Press Body Motor. Tiket ${item.nomor_tiket}.`; const wa = whatsappLink(item, message); return `<article class="queue-card status-${safe(item.status)}"><div class="queue-card-top"><strong>${safe(item.nomor_tiket)}</strong><span class="queue-status">${safe(item.status)}</span></div><p><b>${safe(item.pelanggan?.nama)}</b> · ${safe(item.kendaraan?.nomor_polisi)} (${safe(item.kendaraan?.merk)} ${safe(item.kendaraan?.tipe)})</p><div class="queue-card-meta"><span>${safe(item.layanan?.nama_layanan)}</span><span>${timeText}</span><span>${new Intl.DateTimeFormat('id-ID', { hour: '2-digit', minute: '2-digit' }).format(new Date(item.jadwal_mulai))}</span></div><div class="queue-card-actions">${statusButton(item)}${item.status === 'selesai' ? `<a href="${wa}" target="_blank" rel="noreferrer">Kirim WhatsApp</a>` : ''}</div></article>`; }
function renderQueues() { const nowKey = today(); const relevant = state.queue.filter(item => queueDate(item) >= nowKey && item.status !== 'dipanggil'); const bookings = relevant.filter(item => item.tipe_kedatangan === 'booking'); const walkins = relevant.filter(item => item.tipe_kedatangan === 'walk-in' && queueDate(item) === nowKey); document.getElementById('booking-count').textContent = bookings.length; document.getElementById('walkin-count').textContent = walkins.length; document.getElementById('booking-list').innerHTML = bookings.map(renderQueueCard).join('') || '<div class="queue-empty">Belum ada booking mendatang.</div>'; document.getElementById('walkin-list').innerHTML = walkins.map(renderQueueCard).join('') || '<div class="queue-empty">Belum ada unit walk-in hari ini.</div>'; document.querySelectorAll('[data-queue-status]').forEach(button => button.addEventListener('click', async () => { button.disabled = true; try { await api(`/antrian/${button.dataset.queueId}`, { method: 'PATCH', body: JSON.stringify({ status: button.dataset.queueStatus }) }); await loadOperations(); } catch (error) { button.disabled = false; alert(error.message); } })); document.querySelectorAll('[data-call-id]').forEach(button => button.addEventListener('click', async () => { const item = state.queue.find(entry => entry.id === button.dataset.callId); if (!item) return; try { await api(`/antrian/${item.id}`, { method: 'PATCH', body: JSON.stringify({ status: 'dipanggil' }) }); callCustomer(item); await loadOperations(); } catch (error) { alert(error.message); } })); const completed = state.queue.filter(item => item.status === 'selesai').slice(0, 3); document.getElementById('completed-alert').innerHTML = completed.length ? `<p class="eyebrow">SIAP DIPANGGIL</p>${completed.map(item => `<div class="alert-line"><span><b>${safe(item.nomor_tiket)}</b> · ${safe(item.pelanggan?.nama)} · ${safe(item.kendaraan?.nomor_polisi)}</span><button data-quick-call="${safe(item.id)}">Panggil ↗</button></div>`).join('')}` : '<p class="muted">Belum ada unit selesai yang menunggu panggilan.</p>'; document.querySelectorAll('[data-quick-call]').forEach(button => button.addEventListener('click', async () => { const item = state.queue.find(entry => entry.id === button.dataset.quickCall); if (!item) return; callCustomer(item); await api(`/antrian/${item.id}`, { method: 'PATCH', body: JSON.stringify({ status: 'dipanggil' }) }); await loadOperations(); })); updateOperationalMetrics(); renderCalendar(); renderCashQueueOptions(); }
function renderCashQueueOptions() { const select = document.getElementById('cash-queue-source'); const alreadyPaid = new Set(state.incomes.map(row => row.antrian_id).filter(Boolean)); const completed = state.queue.filter(item => ['selesai', 'dipanggil'].includes(item.status) && !alreadyPaid.has(item.id)); select.innerHTML = '<option value="">Pilih tiket selesai</option>' + completed.map(item => `<option value="${safe(item.id)}">${safe(item.nomor_tiket)} · ${safe(item.pelanggan?.nama)} · ${safe(item.kendaraan?.nomor_polisi)}</option>`).join(''); }
async function loadOperations() { try { state.queue = await api('/antrian'); state.queueReady = true; renderQueues(); } catch (error) { state.queue = []; state.queueReady = false; renderQueues(); document.getElementById('booking-list').innerHTML = '<div class="queue-empty">Fitur booking belum aktif. Jalankan database/operational-features.sql di Supabase, lalu refresh aplikasi.</div>'; updateOperationalMetrics(); } }
function localDateTime(date = new Date()) { const pad = value => String(value).padStart(2, '0'); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`; }
function fillQueueFormOptions() { fillSelect('queue-customer', state.customers, 'pelanggan'); fillSelect('queue-vehicle', [], 'kendaraan'); fillSelect('queue-service', state.services, 'layanan'); }
document.getElementById('calendar-days').addEventListener('click', event => { const button = event.target.closest('[data-calendar-date]'); if (!button) return; state.selectedCalendarDate = button.dataset.calendarDate; renderCalendar(); });
document.getElementById('calendar-prev').addEventListener('click', () => { state.calendarCursor.setMonth(state.calendarCursor.getMonth() - 1); renderCalendar(); });
document.getElementById('calendar-next').addEventListener('click', () => { state.calendarCursor.setMonth(state.calendarCursor.getMonth() + 1); renderCalendar(); });
document.getElementById('book-selected-day').addEventListener('click', () => { location.hash = '#layanan'; document.getElementById('arrival-type').value = 'booking'; document.getElementById('queue-datetime').value = `${state.selectedCalendarDate}T09:00`; document.getElementById('queue-datetime-label').firstChild.textContent = 'Jadwal booking'; setTimeout(() => document.getElementById('queue-form').scrollIntoView({ behavior: 'smooth', block: 'center' }), 120); });
document.getElementById('queue-customer').addEventListener('change', event => { fillSelect('queue-vehicle', state.vehicles.filter(vehicle => vehicle.pelanggan_id === event.target.value), 'kendaraan'); });
document.getElementById('arrival-type').addEventListener('change', event => { const booking = event.target.value === 'booking'; document.getElementById('queue-datetime-label').firstChild.textContent = booking ? 'Jadwal booking' : 'Waktu masuk'; document.getElementById('queue-datetime').value = booking ? `${state.selectedCalendarDate}T09:00` : localDateTime(); });
document.getElementById('queue-form').addEventListener('submit', async event => { event.preventDefault(); const message = document.getElementById('queue-message'); message.textContent = ''; const data = Object.fromEntries(new FormData(event.currentTarget)); data.jadwal_mulai = new Date(data.jadwal_mulai).toISOString(); try { const inserted = await api('/antrian', { method: 'POST', body: JSON.stringify(data) }); message.style.color = '#3d9863'; message.textContent = `Nomor antrean ${inserted[0]?.nomor_tiket || 'berhasil dibuat'}.`; event.currentTarget.reset(); document.getElementById('queue-datetime').value = localDateTime(); fillQueueFormOptions(); await loadOperations(); } catch (error) { message.style.color = 'var(--red)'; message.textContent = error.message; } });
document.getElementById('cash-queue-source').addEventListener('change', event => { const item = state.queue.find(entry => entry.id === event.target.value); state.selectedQueue = item || null; if (!item) return; document.getElementById('customer-id').value = item.pelanggan_id; fillVehicleSelect(item.pelanggan_id); document.getElementById('vehicle-id').value = item.kendaraan_id; document.getElementById('service-id').value = item.layanan_id; document.getElementById('amount').value = item.layanan?.harga_standar || ''; document.getElementById('income-date').value = today(); });
function reportRows() { const period = document.getElementById('report-period').value; const method = document.getElementById('report-method').value; const date = document.getElementById('report-date').value || today(); const selected = new Date(`${date}T12:00:00`); const from = new Date(selected); if (period === 'weekly') from.setDate(from.getDate() - 6); const rows = state.incomes.filter(row => { const key = row.tanggal; const dateMatch = period === 'all' || (period === 'daily' && key === date) || (period === 'weekly' && key >= dateKey(from) && key <= date) || (period === 'monthly' && key.slice(0, 7) === date.slice(0, 7)); return dateMatch && (method === 'all' || row.metode_pembayaran === method); }); document.getElementById('report-total').textContent = currency.format(rows.reduce((total, row) => total + Number(row.total), 0)); document.getElementById('report-rows').innerHTML = rows.map(row => `<tr><td>${safe(row.tanggal)}</td><td>${safe(row.nomor_transaksi)}</td><td>${safe(row.pelanggan?.nama || '-')}</td><td>${safe(row.metode_pembayaran || '-')}</td><td class="align-right amount">${currency.format(row.total)}</td></tr>`).join('') || '<tr><td colspan="5" class="empty-state">Tidak ada transaksi sesuai filter.</td></tr>'; return rows; }
function downloadReport() { const rows = reportRows(); const csv = [['Tanggal', 'Nomor Transaksi', 'Pelanggan', 'Metode Pembayaran', 'Total'], ...rows.map(row => [row.tanggal, row.nomor_transaksi, row.pelanggan?.nama || '', row.metode_pembayaran || '', row.total])].map(line => line.map(value => `"${String(value).replace(/"/g, '""')}"`).join(',')).join('\r\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob(['\ufeff', csv], { type: 'text/csv;charset=utf-8' })); link.download = `laporan-pendapatan-${today()}.csv`; link.click(); URL.revokeObjectURL(link.href); }
function printPage(title, content, pageCss = '') { const popup = window.open('', '_blank', 'width=520,height=720'); if (!popup) return alert('Izinkan pop-up untuk mencetak nota/laporan.'); popup.document.write(`<!doctype html><html><head><title>${safe(title)}</title><style>body{font:12px Arial,sans-serif;margin:18px;color:#111}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:6px;border-bottom:1px solid #ddd}.right{text-align:right}@page{${pageCss}}</style></head><body>${content}<script>window.onload=()=>window.print()<\/script></body></html>`); popup.document.close(); }
function receiptHtml(item) { return `<div class="invoice-body"><h1>PRESS BODY MOTOR</h1><p style="text-align:center">Bukti pembayaran jasa bengkel</p><hr><p>No: ${safe(item.nomor_transaksi)}</p><p>Tanggal: ${safe(item.tanggal)}</p><p>Pelanggan: ${safe(item.pelangganName)}</p><p>Kendaraan: ${safe(item.plate)}</p><p>Layanan: ${safe(item.serviceName)}</p><p>Metode: ${safe(item.method)}</p><hr><p class="invoice-total">TOTAL: ${currency.format(item.total)}</p><hr><p style="text-align:center">Terima kasih atas kepercayaan Anda.</p></div>`; }
function printLastReceipt() { const item = state.lastReceipt; if (!item) return alert('Simpan transaksi terlebih dahulu untuk membuat nota.'); const html = receiptHtml(item); document.getElementById('receipt-preview').innerHTML = html; const format = document.getElementById('receipt-format').value; const page = format === 'pdf' ? 'size: A4; margin: 14mm' : `size: ${format === 'thermal80' ? '80mm' : '58mm'} 200mm; margin: 4mm`; printPage('Nota Press Body Motor', html, page); }
document.getElementById('print-receipt').addEventListener('click', printLastReceipt);
const receiptFormat = document.createElement('select'); receiptFormat.id = 'receipt-format'; receiptFormat.className = 'select'; receiptFormat.setAttribute('aria-label', 'Format nota'); receiptFormat.innerHTML = '<option value="thermal58">Thermal 58 mm</option><option value="thermal80">Thermal 80 mm</option><option value="pdf">E-Nota A4 / PDF</option>'; document.querySelector('.receipt-actions').prepend(receiptFormat);
document.getElementById('send-receipt-wa').addEventListener('click', () => { const item = state.lastReceipt; if (!item) return alert('Simpan transaksi terlebih dahulu untuk mengirim nota.'); const customer = state.customers.find(entry => entry.id === item.customerId); const text = `Terima kasih ${item.pelangganName}. Pembayaran ${item.nomor_transaksi} sebesar ${currency.format(item.total)} (${item.serviceName}, ${item.plate}) telah diterima. Press Body Motor.`; window.open(`https://wa.me/${phoneNumber(customer?.no_telepon)}?text=${encodeURIComponent(text)}`, '_blank', 'noopener'); });
document.getElementById('report-period').addEventListener('change', reportRows); document.getElementById('report-method').addEventListener('change', reportRows); document.getElementById('report-date').addEventListener('change', reportRows); document.getElementById('export-report').addEventListener('click', downloadReport); document.getElementById('print-report').addEventListener('click', () => { const rows = reportRows(); const html = `<h1>Laporan Pendapatan Bengkel</h1><table><thead><tr><th>Tanggal</th><th>Transaksi</th><th>Pelanggan</th><th>Metode</th><th class="right">Total</th></tr></thead><tbody>${rows.map(row => `<tr><td>${safe(row.tanggal)}</td><td>${safe(row.nomor_transaksi)}</td><td>${safe(row.pelanggan?.nama || '-')}</td><td>${safe(row.metode_pembayaran || '-')}</td><td class="right">${currency.format(row.total)}</td></tr>`).join('')}</tbody></table><h3>Total: ${document.getElementById('report-total').textContent}</h3>`; printPage('Laporan Pendapatan', html); });
const originalIncomeSubmit = document.getElementById('income-form');
originalIncomeSubmit.addEventListener('submit', async event => { event.preventDefault(); event.stopImmediatePropagation(); const message = document.getElementById('form-message'); message.textContent = ''; const item = state.selectedQueue; const payload = { pelanggan_id: document.getElementById('customer-id').value, kendaraan_id: document.getElementById('vehicle-id').value, layanan_id: document.getElementById('service-id').value, total: Number(document.getElementById('amount').value), tanggal: document.getElementById('income-date').value, metode_pembayaran: document.getElementById('payment-method').value, antrian_id: item?.id || null }; try { const inserted = await api('/pendapatan', { method: 'POST', body: JSON.stringify(payload) }); const service = state.services.find(entry => entry.id === payload.layanan_id); const customer = state.customers.find(entry => entry.id === payload.pelanggan_id); const vehicle = state.vehicles.find(entry => entry.id === payload.kendaraan_id); state.lastReceipt = { ...(Array.isArray(inserted) ? inserted[0] : inserted), total: payload.total, tanggal: payload.tanggal, method: payload.metode_pembayaran, pelangganName: customer?.nama || '', customerId: payload.pelanggan_id, plate: vehicle?.nomor_polisi || '', serviceName: service?.nama_layanan || '' }; document.getElementById('receipt-preview').innerHTML = receiptHtml(state.lastReceipt); message.style.color = '#3d9863'; message.textContent = 'Pembayaran tersimpan. Nota siap dicetak atau dikirim.'; state.selectedQueue = null; event.currentTarget.reset(); document.getElementById('income-date').value = today(); document.getElementById('cash-queue-source').value = ''; await loadData(); await loadOperations(); reportRows(); } catch (error) { message.style.color = 'var(--red)'; message.textContent = error.message; } }, true);
document.getElementById('report-date').value = today(); document.getElementById('queue-datetime').value = localDateTime(); reportRows(); setInterval(() => { if (state.queueReady) loadOperations(); }, 20000); setInterval(() => { if (state.queueReady && state.queue.length) renderQueues(); }, 60000);
